/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 earth.gltf 
Author: ig.ghazigfx (https://sketchfab.com/ig.ghazigfx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2022-rolls-royce-phantom-extended-series-ii-1923bdcbc32f442e97dd49201aa2c928
Title: 2022 Rolls-Royce Phantom Extended Series II
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import { useFrame, useThree } from "@react-three/fiber";

import gsap from "gsap";
import { useRef, useEffect } from "react";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/earth.gltf");
  const modelRef = useRef();
  const modelRef2 = useRef();
  const { invalidate } = useThree();
  useEffect(() => {
    gsap.fromTo(
      modelRef.current.scale,
      { x: 0.5, y: 0.5, z: 0.5 },
      {
        x: 1,
        y: 1,
        z: 1,
        duration: 2,
        translateX: 200,
        ease: "Ease-out" /*"elastic.out(1, 0.3)"*/,
      }
    );
    gsap.to(modelRef2.current.position, {
      // z: Math.PI / 40,
      // y: -0.2,
      // z: -0.2,
      // ease: "power1.inOut",
      // duration: 2,
    });
    gsap.to(modelRef.current.rotation, {
      y: 1.1,
      duration: 2,
      repeat: 0,
      yoyo: true,
    });
  }, []);
  useFrame(() => {
    if (modelRef.current) {
      // modelRef.current.rotation.y += 0.01; // Rotate for demo
      invalidate(); // Trigger render
    }
  });
  return (
    <group ref={modelRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <group rotation={[Math.PI / 2, 0, 0]} ref={modelRef2}>
          <group position={[-3.449, -0.013, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials["Material.002"]}
              clasName="roll-cube"
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group position={[-3.449, -0.013, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_17.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group position={[-3.449, -0.013, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Object_31.geometry}
              material={materials["Material.007"]}
            />
          </group>
          <group position={[-3.449, -0.013, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Object_35.geometry}
              material={materials["Material.007"]}
            />
          </group>
          <group position={[-3.449, -0.013, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_37.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Object_38.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Object_39.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Object_40.geometry}
              material={materials["Material.007"]}
            />
          </group>
          <group position={[-3.449, -0.013, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_42.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Object_43.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Object_44.geometry}
              material={materials["Material.007"]}
            />
          </group>
          <group position={[-3.449, -0.013, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_47.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_49.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_50.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_51.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <group position={[-3.449, -0.013, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_53.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_55.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_56.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_57.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              geometry={nodes.Object_58.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <group position={[-3.449, -0.013, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_70.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              geometry={nodes.Object_71.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials["Material.005"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials["Material.004"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials["Material.008"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials["Material.010"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials["Material.007"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials["Material.013"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials["Material.007"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_60.geometry}
            material={materials["Material.007"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_62.geometry}
            material={materials["Material.006"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_64.geometry}
            material={materials["Material.004"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_66.geometry}
            material={materials["Material.014"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_68.geometry}
            material={materials["Material.001"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_73.geometry}
            material={materials["Material.015"]}
            position={[-3.449, -0.013, -0.01]}
            scale={0.001}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/earth.gltf");
